# These are supported funding model platforms

github: LevaComp
patreon: lev_bul
open_collective: Leva
ko_fi: lev_BUL
liberapay: lev_bul
issuehunt: levacompany
custom: ["paypal.me/levacomp", levabrands.dev]
